Added Account and Transaction entities, the repository and service levels for them
Vedroid/jv-bank-service pull request #2
Opened 2021-03-01 21:46 UTC by Vedroid

2021-03-02 06:59 UTC, Mandybur800 requested changes

2021-03-02 06:59 UTC, Mandybur800 commented on src/main/java/ua/vedroid/bankservice/entity/Account.java
> +    private Double balance;
We need BigDecimal

2021-03-02 06:59 UTC, Mandybur800 commented on src/main/java/ua/vedroid/bankservice/entity/Account.java
> +    private Double balance;
and add some constrains

2021-03-02 06:59 UTC, Mandybur800 commented on src/main/java/ua/vedroid/bankservice/entity/Transaction.java
> +    private Double amount;
same

2021-03-02 06:59 UTC, Mandybur800 commented on src/main/java/ua/vedroid/bankservice/util/CurrencyConverter.java
> +}
just remove this class, because it is part 3

2021-03-02 07:57 UTC, Vedroid commented on src/main/java/ua/vedroid/bankservice/entity/Account.java
> +    private Double balance;
I know that floating point numbers cannot be used for precise calculations. But the assignment says double
![image](https://user-images.githubusercontent.com/2052362/109616362-bd0e8900-7b3d-11eb-8f42-588cd8ea2ef3.png)

2021-03-02 10:17 UTC, boroda4436 commented on src/main/java/ua/vedroid/bankservice/entity/Account.java
> +    private Double balance;
@Vedroid Sorry, our fault. Better use BigDeimal

2021-03-02 12:38 UTC, boroda4436 requested changes

2021-03-02 12:38 UTC, boroda4436 commented on src/main/java/ua/vedroid/bankservice/repository/AccountRepository.java
> +    @Transactional
@Vedroid we don't need to add this annotation to the repository methods. Better add this annotation on the service layer if you have multiple read/write operations in that method

2021-03-02 15:37 UTC, KseniiaMakarova requested changes

2021-03-02 15:37 UTC, KseniiaMakarova commented on pom.xml
> +            <artifactId>gson</artifactId>
do you use this at this point?

2021-03-02 15:37 UTC, KseniiaMakarova commented on src/main/java/ua/vedroid/bankservice/repository/AccountRepository.java
> +    List<Account> findAllByUserPhoneNumber(String phoneNumber);
does it work without `@Query` annotation?

2021-03-02 15:37 UTC, KseniiaMakarova commented on src/main/java/ua/vedroid/bankservice/repository/AccountRepository.java
> +    Optional<Account> findByAccountNumber(String accountNumber);
same - won't the user be fetched by default here?

2021-03-02 15:37 UTC, KseniiaMakarova commented on src/main/java/ua/vedroid/bankservice/repository/AccountRepository.java
> +    void blockByAccountNumber(String accountNumber);
let's better set `active` to false somewhere in constructor and then just call `save()`?

2021-03-02 15:37 UTC, KseniiaMakarova commented on src/main/java/ua/vedroid/bankservice/repository/TransactionRepository.java
> +            + "WHERE fa.accountNumber = ?1 OR ta.accountNumber = ?1")
is it obligatory to do join fetch here?

2021-03-02 15:37 UTC, KseniiaMakarova commented on src/main/java/ua/vedroid/bankservice/service/AccountService.java
> +    Account create(Account account);
```suggestion
    Account save(Account account);
```

2021-03-02 15:37 UTC, KseniiaMakarova commented on src/main/java/ua/vedroid/bankservice/service/impl/TransactionServiceImpl.java
> +        toAccount.setBalance(toAccount.getBalance().add(amount));
are you saving the updated balance?

2021-03-02 15:37 UTC, KseniiaMakarova commented on src/main/java/ua/vedroid/bankservice/service/impl/TransactionServiceImpl.java
> +                .of(page - 1, limit, Sort.by("date").descending().and(Sort.by("id")));
why -1?

2021-03-02 16:47 UTC, Vedroid commented on src/main/java/ua/vedroid/bankservice/service/impl/TransactionServiceImpl.java
> +                .of(page - 1, limit, Sort.by("date").descending().and(Sort.by("id")));
I wanted Page numbering to start at 1 `/accounts/history/13?page=1`. But it’s probably better not to do it

2021-03-02 20:25 UTC, Vedroid commented on src/main/java/ua/vedroid/bankservice/repository/AccountRepository.java
> +    List<Account> findAllByUserPhoneNumber(String phoneNumber);
This is how one request to the database happens instead of two.

2021-03-03 08:24 UTC, KseniiaMakarova approved these changes

2021-03-03 13:54 UTC, merged